services:
  database:
    image: postgres:17
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: mafia-api
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DATABASE_USER}"]
      start_period: 15s
      start_interval: 1s
      interval: 30s
      timeout: 5s
      retries: 3
  migrations:
    image: "${DOCKER_IMAGE_NAME_MIGRATIONS:-ghcr.io/nekoalice42/mafia-companion-api/migrations}:${DOCKER_IMAGE_TAG_MIGRATIONS:-latest}"
    environment: &db-env
      DATABASE_URL: postgresql://database/mafia-api
      DATABASE_USER:
      DATABASE_PASSWORD:
    depends_on:
      database:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
  cleaner:
    image: "${DOCKER_IMAGE_NAME_CLEANER:-ghcr.io/nekoalice42/mafia-companion-api/cleaner}:${DOCKER_IMAGE_TAG_CLEANER:-latest}"
    environment:
      <<: *db-env
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
  server:
    image: "${DOCKER_IMAGE_NAME_SERVER:-ghcr.io/nekoalice42/mafia-companion-api/server}:${DOCKER_IMAGE_TAG_SERVER:-latest}"
    environment:
      <<: *db-env
      TELEGRAM_OIDC_CLIENT_ID:
      TELEGRAM_OIDC_CLIENT_SECRET:
      TELEGRAM_OIDC_REDIRECT_HOST:
      TELEGRAM_OIDC_STATE_SECRET:
    depends_on:
      database:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    healthcheck:
      test: ["CMD", "/usr/bin/env", "curl", "-f", "http://127.0.0.1:8080/"]
      start_period: 10s
      start_interval: 1s
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  database:
