services:
  server:
    environment:
      TELEGRAM_OIDC_REDIRECT_HOST: https://api.mafia.nekoalice.me
    labels:
      traefik.enable: "true"
      traefik.http.routers.mafia-api.rule: "Host(`api.mafia.nekoalice.me`)"
    networks:
      - default
      - services

networks:
  services:
    name: docker-services
    external: true
